<?xml version="1.0" encoding="utf-8"?><Database Name="ASPNETMVC" Class="DBBugstoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-H1GSGD4;Initial Catalog=ASPNETMVC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ASPNETMVCConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_admin" Member="tbl_admins">
    <Type Name="tbl_admin">
      <Column Name="username_admin" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password_admin" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name_admin" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="phone_admin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email_admin" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="level_admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_brand" Member="tbl_brands">
    <Type Name="tbl_brand">
      <Column Name="id_brand" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_brand" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_brand_tbl_product" Member="tbl_products" ThisKey="id_brand" OtherKey="id_brand" Type="tbl_product" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_cat" Member="tbl_cats">
    <Type Name="tbl_cat">
      <Column Name="id_cat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name_product" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ssid_cat" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price_product" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="size_product" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quantity_cat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="image_product" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_customer_tbl_cat" Member="tbl_customer" ThisKey="id_customer" OtherKey="id_customer" Type="tbl_customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_category" Member="tbl_categories">
    <Type Name="tbl_category">
      <Column Name="id_category" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_category" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="size_category" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_category_tbl_product" Member="tbl_products" ThisKey="id_category" OtherKey="id_category" Type="tbl_product" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_city" Member="tbl_cities">
    <Type Name="tbl_city">
      <Column Name="id_city" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_city" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="type_city" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="tbl_city_tbl_district" Member="tbl_districts" ThisKey="id_city" OtherKey="id_city" Type="tbl_district" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_customer" Member="tbl_customers">
    <Type Name="tbl_customer">
      <Column Name="id_customer" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username_customer" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password_customer" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name_customer" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email_customer" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="phone_customer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="city_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="district_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_customer_tbl_cat" Member="tbl_cats" ThisKey="id_customer" OtherKey="id_customer" Type="tbl_cat" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_district" Member="tbl_districts">
    <Type Name="tbl_district">
      <Column Name="id_district" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_district" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="type_district" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="id_city" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="tbl_city_tbl_district" Member="tbl_city" ThisKey="id_city" OtherKey="id_city" Type="tbl_city" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_order" Member="tbl_orders">
    <Type Name="tbl_order">
      <Column Name="id_order" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date_order" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="buyer_order" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="consignee_order" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="phone_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="address_order" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="totalprice_order" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="status_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_order_tbl_orderdetail" Member="tbl_orderdetails" ThisKey="id_order" OtherKey="id_order" Type="tbl_orderdetail" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_orderdetails" Member="tbl_orderdetails">
    <Type Name="tbl_orderdetail">
      <Column Name="id_details" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name_product" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="size_product" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="quantity_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="image_product" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="price_product" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="tbl_order_tbl_orderdetail" Member="tbl_order" ThisKey="id_order" OtherKey="id_order" Type="tbl_order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_product" Member="tbl_products">
    <Type Name="tbl_product">
      <Column Name="id_product" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_product" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id_category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_brand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="size_product" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="price_product" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="image_product" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity_product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type_product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="discription_product" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tbl_brand_tbl_product" Member="tbl_brand" ThisKey="id_brand" OtherKey="id_brand" Type="tbl_brand" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="tbl_category_tbl_product" Member="tbl_category" ThisKey="id_category" OtherKey="id_category" Type="tbl_category" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>