#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugStore.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETMVC")]
	public partial class DBBugstoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_admin(tbl_admin instance);
    partial void Updatetbl_admin(tbl_admin instance);
    partial void Deletetbl_admin(tbl_admin instance);
    partial void Inserttbl_brand(tbl_brand instance);
    partial void Updatetbl_brand(tbl_brand instance);
    partial void Deletetbl_brand(tbl_brand instance);
    partial void Inserttbl_cat(tbl_cat instance);
    partial void Updatetbl_cat(tbl_cat instance);
    partial void Deletetbl_cat(tbl_cat instance);
    partial void Inserttbl_category(tbl_category instance);
    partial void Updatetbl_category(tbl_category instance);
    partial void Deletetbl_category(tbl_category instance);
    partial void Inserttbl_customer(tbl_customer instance);
    partial void Updatetbl_customer(tbl_customer instance);
    partial void Deletetbl_customer(tbl_customer instance);
    partial void Inserttbl_order(tbl_order instance);
    partial void Updatetbl_order(tbl_order instance);
    partial void Deletetbl_order(tbl_order instance);
    partial void Inserttbl_orderdetail(tbl_orderdetail instance);
    partial void Updatetbl_orderdetail(tbl_orderdetail instance);
    partial void Deletetbl_orderdetail(tbl_orderdetail instance);
    partial void Inserttbl_product(tbl_product instance);
    partial void Updatetbl_product(tbl_product instance);
    partial void Deletetbl_product(tbl_product instance);
    #endregion
		
		public DBBugstoreDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETMVCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBBugstoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBugstoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBugstoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBugstoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_admin> tbl_admins
		{
			get
			{
				return this.GetTable<tbl_admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_brand> tbl_brands
		{
			get
			{
				return this.GetTable<tbl_brand>();
			}
		}
		
		public System.Data.Linq.Table<tbl_cat> tbl_cats
		{
			get
			{
				return this.GetTable<tbl_cat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_category> tbl_categories
		{
			get
			{
				return this.GetTable<tbl_category>();
			}
		}
		
		public System.Data.Linq.Table<tbl_customer> tbl_customers
		{
			get
			{
				return this.GetTable<tbl_customer>();
			}
		}
		
		public System.Data.Linq.Table<tbl_order> tbl_orders
		{
			get
			{
				return this.GetTable<tbl_order>();
			}
		}
		
		public System.Data.Linq.Table<tbl_orderdetail> tbl_orderdetails
		{
			get
			{
				return this.GetTable<tbl_orderdetail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_product> tbl_products
		{
			get
			{
				return this.GetTable<tbl_product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_admin")]
	public partial class tbl_admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username_admin;
		
		private string _password_admin;
		
		private string _name_admin;
		
		private int _phone_admin;
		
		private string _email_admin;
		
		private System.Nullable<int> _level_admin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusername_adminChanging(string value);
    partial void Onusername_adminChanged();
    partial void Onpassword_adminChanging(string value);
    partial void Onpassword_adminChanged();
    partial void Onname_adminChanging(string value);
    partial void Onname_adminChanged();
    partial void Onphone_adminChanging(int value);
    partial void Onphone_adminChanged();
    partial void Onemail_adminChanging(string value);
    partial void Onemail_adminChanged();
    partial void Onlevel_adminChanging(System.Nullable<int> value);
    partial void Onlevel_adminChanged();
    #endregion
		
		public tbl_admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_admin", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username_admin
		{
			get
			{
				return this._username_admin;
			}
			set
			{
				if ((this._username_admin != value))
				{
					this.Onusername_adminChanging(value);
					this.SendPropertyChanging();
					this._username_admin = value;
					this.SendPropertyChanged("username_admin");
					this.Onusername_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_admin", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string password_admin
		{
			get
			{
				return this._password_admin;
			}
			set
			{
				if ((this._password_admin != value))
				{
					this.Onpassword_adminChanging(value);
					this.SendPropertyChanging();
					this._password_admin = value;
					this.SendPropertyChanged("password_admin");
					this.Onpassword_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_admin", DbType="NVarChar(255)")]
		public string name_admin
		{
			get
			{
				return this._name_admin;
			}
			set
			{
				if ((this._name_admin != value))
				{
					this.Onname_adminChanging(value);
					this.SendPropertyChanging();
					this._name_admin = value;
					this.SendPropertyChanged("name_admin");
					this.Onname_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_admin", DbType="Int NOT NULL")]
		public int phone_admin
		{
			get
			{
				return this._phone_admin;
			}
			set
			{
				if ((this._phone_admin != value))
				{
					this.Onphone_adminChanging(value);
					this.SendPropertyChanging();
					this._phone_admin = value;
					this.SendPropertyChanged("phone_admin");
					this.Onphone_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_admin", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email_admin
		{
			get
			{
				return this._email_admin;
			}
			set
			{
				if ((this._email_admin != value))
				{
					this.Onemail_adminChanging(value);
					this.SendPropertyChanging();
					this._email_admin = value;
					this.SendPropertyChanged("email_admin");
					this.Onemail_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_admin", DbType="Int")]
		public System.Nullable<int> level_admin
		{
			get
			{
				return this._level_admin;
			}
			set
			{
				if ((this._level_admin != value))
				{
					this.Onlevel_adminChanging(value);
					this.SendPropertyChanging();
					this._level_admin = value;
					this.SendPropertyChanged("level_admin");
					this.Onlevel_adminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_brand")]
	public partial class tbl_brand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_brand;
		
		private string _name_brand;
		
		private EntitySet<tbl_product> _tbl_products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_brandChanging(int value);
    partial void Onid_brandChanged();
    partial void Onname_brandChanging(string value);
    partial void Onname_brandChanged();
    #endregion
		
		public tbl_brand()
		{
			this._tbl_products = new EntitySet<tbl_product>(new Action<tbl_product>(this.attach_tbl_products), new Action<tbl_product>(this.detach_tbl_products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_brand", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_brand
		{
			get
			{
				return this._id_brand;
			}
			set
			{
				if ((this._id_brand != value))
				{
					this.Onid_brandChanging(value);
					this.SendPropertyChanging();
					this._id_brand = value;
					this.SendPropertyChanged("id_brand");
					this.Onid_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_brand", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name_brand
		{
			get
			{
				return this._name_brand;
			}
			set
			{
				if ((this._name_brand != value))
				{
					this.Onname_brandChanging(value);
					this.SendPropertyChanging();
					this._name_brand = value;
					this.SendPropertyChanged("name_brand");
					this.Onname_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_brand_tbl_product", Storage="_tbl_products", ThisKey="id_brand", OtherKey="id_brand")]
		public EntitySet<tbl_product> tbl_products
		{
			get
			{
				return this._tbl_products;
			}
			set
			{
				this._tbl_products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_products(tbl_product entity)
		{
			this.SendPropertyChanging();
			entity.tbl_brand = this;
		}
		
		private void detach_tbl_products(tbl_product entity)
		{
			this.SendPropertyChanging();
			entity.tbl_brand = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cat")]
	public partial class tbl_cat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cat;
		
		private System.Nullable<int> _id_customer;
		
		private string _name_product;
		
		private string _ssid_cat;
		
		private System.Nullable<long> _price_product;
		
		private string _size_product;
		
		private System.Nullable<int> _quantity_cat;
		
		private string _image_product;
		
		private EntityRef<tbl_customer> _tbl_customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_catChanging(int value);
    partial void Onid_catChanged();
    partial void Onid_customerChanging(System.Nullable<int> value);
    partial void Onid_customerChanged();
    partial void Onname_productChanging(string value);
    partial void Onname_productChanged();
    partial void Onssid_catChanging(string value);
    partial void Onssid_catChanged();
    partial void Onprice_productChanging(System.Nullable<long> value);
    partial void Onprice_productChanged();
    partial void Onsize_productChanging(string value);
    partial void Onsize_productChanged();
    partial void Onquantity_catChanging(System.Nullable<int> value);
    partial void Onquantity_catChanged();
    partial void Onimage_productChanging(string value);
    partial void Onimage_productChanged();
    #endregion
		
		public tbl_cat()
		{
			this._tbl_customer = default(EntityRef<tbl_customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cat
		{
			get
			{
				return this._id_cat;
			}
			set
			{
				if ((this._id_cat != value))
				{
					this.Onid_catChanging(value);
					this.SendPropertyChanging();
					this._id_cat = value;
					this.SendPropertyChanged("id_cat");
					this.Onid_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					if (this._tbl_customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_product", DbType="NVarChar(255)")]
		public string name_product
		{
			get
			{
				return this._name_product;
			}
			set
			{
				if ((this._name_product != value))
				{
					this.Onname_productChanging(value);
					this.SendPropertyChanging();
					this._name_product = value;
					this.SendPropertyChanged("name_product");
					this.Onname_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ssid_cat", DbType="NVarChar(255)")]
		public string ssid_cat
		{
			get
			{
				return this._ssid_cat;
			}
			set
			{
				if ((this._ssid_cat != value))
				{
					this.Onssid_catChanging(value);
					this.SendPropertyChanging();
					this._ssid_cat = value;
					this.SendPropertyChanged("ssid_cat");
					this.Onssid_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_product", DbType="BigInt")]
		public System.Nullable<long> price_product
		{
			get
			{
				return this._price_product;
			}
			set
			{
				if ((this._price_product != value))
				{
					this.Onprice_productChanging(value);
					this.SendPropertyChanging();
					this._price_product = value;
					this.SendPropertyChanged("price_product");
					this.Onprice_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size_product", DbType="VarChar(20)")]
		public string size_product
		{
			get
			{
				return this._size_product;
			}
			set
			{
				if ((this._size_product != value))
				{
					this.Onsize_productChanging(value);
					this.SendPropertyChanging();
					this._size_product = value;
					this.SendPropertyChanged("size_product");
					this.Onsize_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity_cat", DbType="Int")]
		public System.Nullable<int> quantity_cat
		{
			get
			{
				return this._quantity_cat;
			}
			set
			{
				if ((this._quantity_cat != value))
				{
					this.Onquantity_catChanging(value);
					this.SendPropertyChanging();
					this._quantity_cat = value;
					this.SendPropertyChanged("quantity_cat");
					this.Onquantity_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_product", DbType="VarChar(255)")]
		public string image_product
		{
			get
			{
				return this._image_product;
			}
			set
			{
				if ((this._image_product != value))
				{
					this.Onimage_productChanging(value);
					this.SendPropertyChanging();
					this._image_product = value;
					this.SendPropertyChanged("image_product");
					this.Onimage_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_customer_tbl_cat", Storage="_tbl_customer", ThisKey="id_customer", OtherKey="id_customer", IsForeignKey=true)]
		public tbl_customer tbl_customer
		{
			get
			{
				return this._tbl_customer.Entity;
			}
			set
			{
				tbl_customer previousValue = this._tbl_customer.Entity;
				if (((previousValue != value) 
							|| (this._tbl_customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_customer.Entity = null;
						previousValue.tbl_cats.Remove(this);
					}
					this._tbl_customer.Entity = value;
					if ((value != null))
					{
						value.tbl_cats.Add(this);
						this._id_customer = value.id_customer;
					}
					else
					{
						this._id_customer = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_category")]
	public partial class tbl_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_category;
		
		private string _name_category;
		
		private string _size_category;
		
		private EntitySet<tbl_product> _tbl_products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoryChanging(int value);
    partial void Onid_categoryChanged();
    partial void Onname_categoryChanging(string value);
    partial void Onname_categoryChanged();
    partial void Onsize_categoryChanging(string value);
    partial void Onsize_categoryChanged();
    #endregion
		
		public tbl_category()
		{
			this._tbl_products = new EntitySet<tbl_product>(new Action<tbl_product>(this.attach_tbl_products), new Action<tbl_product>(this.detach_tbl_products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_category", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name_category
		{
			get
			{
				return this._name_category;
			}
			set
			{
				if ((this._name_category != value))
				{
					this.Onname_categoryChanging(value);
					this.SendPropertyChanging();
					this._name_category = value;
					this.SendPropertyChanged("name_category");
					this.Onname_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size_category", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string size_category
		{
			get
			{
				return this._size_category;
			}
			set
			{
				if ((this._size_category != value))
				{
					this.Onsize_categoryChanging(value);
					this.SendPropertyChanging();
					this._size_category = value;
					this.SendPropertyChanged("size_category");
					this.Onsize_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_category_tbl_product", Storage="_tbl_products", ThisKey="id_category", OtherKey="id_category")]
		public EntitySet<tbl_product> tbl_products
		{
			get
			{
				return this._tbl_products;
			}
			set
			{
				this._tbl_products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_products(tbl_product entity)
		{
			this.SendPropertyChanging();
			entity.tbl_category = this;
		}
		
		private void detach_tbl_products(tbl_product entity)
		{
			this.SendPropertyChanging();
			entity.tbl_category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_customer")]
	public partial class tbl_customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_customer;
		
		private string _username_customer;
		
		private string _password_customer;
		
		private string _name_customer;
		
		private string _email_customer;
		
		private int _phone_customer;
		
		private System.Nullable<int> _city_customer;
		
		private System.Nullable<int> _district_customer;
		
		private System.Nullable<int> _address_customer;
		
		private EntitySet<tbl_cat> _tbl_cats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_customerChanging(int value);
    partial void Onid_customerChanged();
    partial void Onusername_customerChanging(string value);
    partial void Onusername_customerChanged();
    partial void Onpassword_customerChanging(string value);
    partial void Onpassword_customerChanged();
    partial void Onname_customerChanging(string value);
    partial void Onname_customerChanged();
    partial void Onemail_customerChanging(string value);
    partial void Onemail_customerChanged();
    partial void Onphone_customerChanging(int value);
    partial void Onphone_customerChanged();
    partial void Oncity_customerChanging(System.Nullable<int> value);
    partial void Oncity_customerChanged();
    partial void Ondistrict_customerChanging(System.Nullable<int> value);
    partial void Ondistrict_customerChanged();
    partial void Onaddress_customerChanging(System.Nullable<int> value);
    partial void Onaddress_customerChanged();
    #endregion
		
		public tbl_customer()
		{
			this._tbl_cats = new EntitySet<tbl_cat>(new Action<tbl_cat>(this.attach_tbl_cats), new Action<tbl_cat>(this.detach_tbl_cats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_customer", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string username_customer
		{
			get
			{
				return this._username_customer;
			}
			set
			{
				if ((this._username_customer != value))
				{
					this.Onusername_customerChanging(value);
					this.SendPropertyChanging();
					this._username_customer = value;
					this.SendPropertyChanged("username_customer");
					this.Onusername_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_customer", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string password_customer
		{
			get
			{
				return this._password_customer;
			}
			set
			{
				if ((this._password_customer != value))
				{
					this.Onpassword_customerChanging(value);
					this.SendPropertyChanging();
					this._password_customer = value;
					this.SendPropertyChanged("password_customer");
					this.Onpassword_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_customer", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name_customer
		{
			get
			{
				return this._name_customer;
			}
			set
			{
				if ((this._name_customer != value))
				{
					this.Onname_customerChanging(value);
					this.SendPropertyChanging();
					this._name_customer = value;
					this.SendPropertyChanged("name_customer");
					this.Onname_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_customer", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email_customer
		{
			get
			{
				return this._email_customer;
			}
			set
			{
				if ((this._email_customer != value))
				{
					this.Onemail_customerChanging(value);
					this.SendPropertyChanging();
					this._email_customer = value;
					this.SendPropertyChanged("email_customer");
					this.Onemail_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_customer", DbType="Int NOT NULL")]
		public int phone_customer
		{
			get
			{
				return this._phone_customer;
			}
			set
			{
				if ((this._phone_customer != value))
				{
					this.Onphone_customerChanging(value);
					this.SendPropertyChanging();
					this._phone_customer = value;
					this.SendPropertyChanged("phone_customer");
					this.Onphone_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_customer", DbType="Int")]
		public System.Nullable<int> city_customer
		{
			get
			{
				return this._city_customer;
			}
			set
			{
				if ((this._city_customer != value))
				{
					this.Oncity_customerChanging(value);
					this.SendPropertyChanging();
					this._city_customer = value;
					this.SendPropertyChanged("city_customer");
					this.Oncity_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district_customer", DbType="Int")]
		public System.Nullable<int> district_customer
		{
			get
			{
				return this._district_customer;
			}
			set
			{
				if ((this._district_customer != value))
				{
					this.Ondistrict_customerChanging(value);
					this.SendPropertyChanging();
					this._district_customer = value;
					this.SendPropertyChanged("district_customer");
					this.Ondistrict_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_customer", DbType="Int")]
		public System.Nullable<int> address_customer
		{
			get
			{
				return this._address_customer;
			}
			set
			{
				if ((this._address_customer != value))
				{
					this.Onaddress_customerChanging(value);
					this.SendPropertyChanging();
					this._address_customer = value;
					this.SendPropertyChanged("address_customer");
					this.Onaddress_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_customer_tbl_cat", Storage="_tbl_cats", ThisKey="id_customer", OtherKey="id_customer")]
		public EntitySet<tbl_cat> tbl_cats
		{
			get
			{
				return this._tbl_cats;
			}
			set
			{
				this._tbl_cats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_cats(tbl_cat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_customer = this;
		}
		
		private void detach_tbl_cats(tbl_cat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_order")]
	public partial class tbl_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_order;
		
		private System.Nullable<System.DateTime> _date_order;
		
		private string _buyer_order;
		
		private string _consignee_order;
		
		private System.Nullable<int> _phone_order;
		
		private string _address_order;
		
		private System.Nullable<long> _totalprice_order;
		
		private System.Nullable<int> _status_order;
		
		private EntitySet<tbl_orderdetail> _tbl_orderdetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_orderChanging(int value);
    partial void Onid_orderChanged();
    partial void Ondate_orderChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_orderChanged();
    partial void Onbuyer_orderChanging(string value);
    partial void Onbuyer_orderChanged();
    partial void Onconsignee_orderChanging(string value);
    partial void Onconsignee_orderChanged();
    partial void Onphone_orderChanging(System.Nullable<int> value);
    partial void Onphone_orderChanged();
    partial void Onaddress_orderChanging(string value);
    partial void Onaddress_orderChanged();
    partial void Ontotalprice_orderChanging(System.Nullable<long> value);
    partial void Ontotalprice_orderChanged();
    partial void Onstatus_orderChanging(System.Nullable<int> value);
    partial void Onstatus_orderChanged();
    #endregion
		
		public tbl_order()
		{
			this._tbl_orderdetails = new EntitySet<tbl_orderdetail>(new Action<tbl_orderdetail>(this.attach_tbl_orderdetails), new Action<tbl_orderdetail>(this.detach_tbl_orderdetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					this.Onid_orderChanging(value);
					this.SendPropertyChanging();
					this._id_order = value;
					this.SendPropertyChanged("id_order");
					this.Onid_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_order", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_order
		{
			get
			{
				return this._date_order;
			}
			set
			{
				if ((this._date_order != value))
				{
					this.Ondate_orderChanging(value);
					this.SendPropertyChanging();
					this._date_order = value;
					this.SendPropertyChanged("date_order");
					this.Ondate_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buyer_order", DbType="NVarChar(255)")]
		public string buyer_order
		{
			get
			{
				return this._buyer_order;
			}
			set
			{
				if ((this._buyer_order != value))
				{
					this.Onbuyer_orderChanging(value);
					this.SendPropertyChanging();
					this._buyer_order = value;
					this.SendPropertyChanged("buyer_order");
					this.Onbuyer_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consignee_order", DbType="NVarChar(255)")]
		public string consignee_order
		{
			get
			{
				return this._consignee_order;
			}
			set
			{
				if ((this._consignee_order != value))
				{
					this.Onconsignee_orderChanging(value);
					this.SendPropertyChanging();
					this._consignee_order = value;
					this.SendPropertyChanged("consignee_order");
					this.Onconsignee_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_order", DbType="Int")]
		public System.Nullable<int> phone_order
		{
			get
			{
				return this._phone_order;
			}
			set
			{
				if ((this._phone_order != value))
				{
					this.Onphone_orderChanging(value);
					this.SendPropertyChanging();
					this._phone_order = value;
					this.SendPropertyChanged("phone_order");
					this.Onphone_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_order", DbType="NVarChar(255)")]
		public string address_order
		{
			get
			{
				return this._address_order;
			}
			set
			{
				if ((this._address_order != value))
				{
					this.Onaddress_orderChanging(value);
					this.SendPropertyChanging();
					this._address_order = value;
					this.SendPropertyChanged("address_order");
					this.Onaddress_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalprice_order", DbType="BigInt")]
		public System.Nullable<long> totalprice_order
		{
			get
			{
				return this._totalprice_order;
			}
			set
			{
				if ((this._totalprice_order != value))
				{
					this.Ontotalprice_orderChanging(value);
					this.SendPropertyChanging();
					this._totalprice_order = value;
					this.SendPropertyChanged("totalprice_order");
					this.Ontotalprice_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_order", DbType="Int")]
		public System.Nullable<int> status_order
		{
			get
			{
				return this._status_order;
			}
			set
			{
				if ((this._status_order != value))
				{
					this.Onstatus_orderChanging(value);
					this.SendPropertyChanging();
					this._status_order = value;
					this.SendPropertyChanged("status_order");
					this.Onstatus_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_order_tbl_orderdetail", Storage="_tbl_orderdetails", ThisKey="id_order", OtherKey="id_order")]
		public EntitySet<tbl_orderdetail> tbl_orderdetails
		{
			get
			{
				return this._tbl_orderdetails;
			}
			set
			{
				this._tbl_orderdetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_orderdetails(tbl_orderdetail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_order = this;
		}
		
		private void detach_tbl_orderdetails(tbl_orderdetail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_orderdetails")]
	public partial class tbl_orderdetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_details;
		
		private System.Nullable<int> _id_order;
		
		private string _name_product;
		
		private string _size_product;
		
		private System.Nullable<int> _quantity_order;
		
		private string _image_product;
		
		private System.Nullable<long> _price_product;
		
		private EntityRef<tbl_order> _tbl_order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detailsChanging(int value);
    partial void Onid_detailsChanged();
    partial void Onid_orderChanging(System.Nullable<int> value);
    partial void Onid_orderChanged();
    partial void Onname_productChanging(string value);
    partial void Onname_productChanged();
    partial void Onsize_productChanging(string value);
    partial void Onsize_productChanged();
    partial void Onquantity_orderChanging(System.Nullable<int> value);
    partial void Onquantity_orderChanged();
    partial void Onimage_productChanging(string value);
    partial void Onimage_productChanged();
    partial void Onprice_productChanging(System.Nullable<long> value);
    partial void Onprice_productChanged();
    #endregion
		
		public tbl_orderdetail()
		{
			this._tbl_order = default(EntityRef<tbl_order>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_details", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_details
		{
			get
			{
				return this._id_details;
			}
			set
			{
				if ((this._id_details != value))
				{
					this.Onid_detailsChanging(value);
					this.SendPropertyChanging();
					this._id_details = value;
					this.SendPropertyChanged("id_details");
					this.Onid_detailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", DbType="Int")]
		public System.Nullable<int> id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					if (this._tbl_order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_orderChanging(value);
					this.SendPropertyChanging();
					this._id_order = value;
					this.SendPropertyChanged("id_order");
					this.Onid_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_product", DbType="NVarChar(255)")]
		public string name_product
		{
			get
			{
				return this._name_product;
			}
			set
			{
				if ((this._name_product != value))
				{
					this.Onname_productChanging(value);
					this.SendPropertyChanging();
					this._name_product = value;
					this.SendPropertyChanged("name_product");
					this.Onname_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size_product", DbType="NVarChar(20)")]
		public string size_product
		{
			get
			{
				return this._size_product;
			}
			set
			{
				if ((this._size_product != value))
				{
					this.Onsize_productChanging(value);
					this.SendPropertyChanging();
					this._size_product = value;
					this.SendPropertyChanged("size_product");
					this.Onsize_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity_order", DbType="Int")]
		public System.Nullable<int> quantity_order
		{
			get
			{
				return this._quantity_order;
			}
			set
			{
				if ((this._quantity_order != value))
				{
					this.Onquantity_orderChanging(value);
					this.SendPropertyChanging();
					this._quantity_order = value;
					this.SendPropertyChanged("quantity_order");
					this.Onquantity_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_product", DbType="VarChar(255)")]
		public string image_product
		{
			get
			{
				return this._image_product;
			}
			set
			{
				if ((this._image_product != value))
				{
					this.Onimage_productChanging(value);
					this.SendPropertyChanging();
					this._image_product = value;
					this.SendPropertyChanged("image_product");
					this.Onimage_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_product", DbType="BigInt")]
		public System.Nullable<long> price_product
		{
			get
			{
				return this._price_product;
			}
			set
			{
				if ((this._price_product != value))
				{
					this.Onprice_productChanging(value);
					this.SendPropertyChanging();
					this._price_product = value;
					this.SendPropertyChanged("price_product");
					this.Onprice_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_order_tbl_orderdetail", Storage="_tbl_order", ThisKey="id_order", OtherKey="id_order", IsForeignKey=true)]
		public tbl_order tbl_order
		{
			get
			{
				return this._tbl_order.Entity;
			}
			set
			{
				tbl_order previousValue = this._tbl_order.Entity;
				if (((previousValue != value) 
							|| (this._tbl_order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_order.Entity = null;
						previousValue.tbl_orderdetails.Remove(this);
					}
					this._tbl_order.Entity = value;
					if ((value != null))
					{
						value.tbl_orderdetails.Add(this);
						this._id_order = value.id_order;
					}
					else
					{
						this._id_order = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_order");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_product")]
	public partial class tbl_product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_product;
		
		private string _name_product;
		
		private System.Nullable<int> _id_category;
		
		private System.Nullable<int> _id_brand;
		
		private string _size_product;
		
		private System.Nullable<long> _price_product;
		
		private string _image_product;
		
		private System.Nullable<int> _quantity_product;
		
		private System.Nullable<int> _type_product;
		
		private string _discription_product;
		
		private EntityRef<tbl_category> _tbl_category;
		
		private EntityRef<tbl_brand> _tbl_brand;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productChanging(int value);
    partial void Onid_productChanged();
    partial void Onname_productChanging(string value);
    partial void Onname_productChanged();
    partial void Onid_categoryChanging(System.Nullable<int> value);
    partial void Onid_categoryChanged();
    partial void Onid_brandChanging(System.Nullable<int> value);
    partial void Onid_brandChanged();
    partial void Onsize_productChanging(string value);
    partial void Onsize_productChanged();
    partial void Onprice_productChanging(System.Nullable<long> value);
    partial void Onprice_productChanged();
    partial void Onimage_productChanging(string value);
    partial void Onimage_productChanged();
    partial void Onquantity_productChanging(System.Nullable<int> value);
    partial void Onquantity_productChanged();
    partial void Ontype_productChanging(System.Nullable<int> value);
    partial void Ontype_productChanged();
    partial void Ondiscription_productChanging(string value);
    partial void Ondiscription_productChanged();
    #endregion
		
		public tbl_product()
		{
			this._tbl_category = default(EntityRef<tbl_category>);
			this._tbl_brand = default(EntityRef<tbl_brand>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_product", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_product
		{
			get
			{
				return this._id_product;
			}
			set
			{
				if ((this._id_product != value))
				{
					this.Onid_productChanging(value);
					this.SendPropertyChanging();
					this._id_product = value;
					this.SendPropertyChanged("id_product");
					this.Onid_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_product", DbType="NVarChar(255)")]
		public string name_product
		{
			get
			{
				return this._name_product;
			}
			set
			{
				if ((this._name_product != value))
				{
					this.Onname_productChanging(value);
					this.SendPropertyChanging();
					this._name_product = value;
					this.SendPropertyChanged("name_product");
					this.Onname_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_category", DbType="Int")]
		public System.Nullable<int> id_category
		{
			get
			{
				return this._id_category;
			}
			set
			{
				if ((this._id_category != value))
				{
					if (this._tbl_category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoryChanging(value);
					this.SendPropertyChanging();
					this._id_category = value;
					this.SendPropertyChanged("id_category");
					this.Onid_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_brand", DbType="Int")]
		public System.Nullable<int> id_brand
		{
			get
			{
				return this._id_brand;
			}
			set
			{
				if ((this._id_brand != value))
				{
					if (this._tbl_brand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_brandChanging(value);
					this.SendPropertyChanging();
					this._id_brand = value;
					this.SendPropertyChanged("id_brand");
					this.Onid_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size_product", DbType="NVarChar(20)")]
		public string size_product
		{
			get
			{
				return this._size_product;
			}
			set
			{
				if ((this._size_product != value))
				{
					this.Onsize_productChanging(value);
					this.SendPropertyChanging();
					this._size_product = value;
					this.SendPropertyChanged("size_product");
					this.Onsize_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_product", DbType="BigInt")]
		public System.Nullable<long> price_product
		{
			get
			{
				return this._price_product;
			}
			set
			{
				if ((this._price_product != value))
				{
					this.Onprice_productChanging(value);
					this.SendPropertyChanging();
					this._price_product = value;
					this.SendPropertyChanged("price_product");
					this.Onprice_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_product", DbType="VarChar(255)")]
		public string image_product
		{
			get
			{
				return this._image_product;
			}
			set
			{
				if ((this._image_product != value))
				{
					this.Onimage_productChanging(value);
					this.SendPropertyChanging();
					this._image_product = value;
					this.SendPropertyChanged("image_product");
					this.Onimage_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity_product", DbType="Int")]
		public System.Nullable<int> quantity_product
		{
			get
			{
				return this._quantity_product;
			}
			set
			{
				if ((this._quantity_product != value))
				{
					this.Onquantity_productChanging(value);
					this.SendPropertyChanging();
					this._quantity_product = value;
					this.SendPropertyChanged("quantity_product");
					this.Onquantity_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_product", DbType="Int")]
		public System.Nullable<int> type_product
		{
			get
			{
				return this._type_product;
			}
			set
			{
				if ((this._type_product != value))
				{
					this.Ontype_productChanging(value);
					this.SendPropertyChanging();
					this._type_product = value;
					this.SendPropertyChanged("type_product");
					this.Ontype_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discription_product", DbType="NVarChar(MAX)")]
		public string discription_product
		{
			get
			{
				return this._discription_product;
			}
			set
			{
				if ((this._discription_product != value))
				{
					this.Ondiscription_productChanging(value);
					this.SendPropertyChanging();
					this._discription_product = value;
					this.SendPropertyChanged("discription_product");
					this.Ondiscription_productChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_category_tbl_product", Storage="_tbl_category", ThisKey="id_category", OtherKey="id_category", IsForeignKey=true, DeleteRule="CASCADE")]
		public tbl_category tbl_category
		{
			get
			{
				return this._tbl_category.Entity;
			}
			set
			{
				tbl_category previousValue = this._tbl_category.Entity;
				if (((previousValue != value) 
							|| (this._tbl_category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_category.Entity = null;
						previousValue.tbl_products.Remove(this);
					}
					this._tbl_category.Entity = value;
					if ((value != null))
					{
						value.tbl_products.Add(this);
						this._id_category = value.id_category;
					}
					else
					{
						this._id_category = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_brand_tbl_product", Storage="_tbl_brand", ThisKey="id_brand", OtherKey="id_brand", IsForeignKey=true, DeleteRule="CASCADE")]
		public tbl_brand tbl_brand
		{
			get
			{
				return this._tbl_brand.Entity;
			}
			set
			{
				tbl_brand previousValue = this._tbl_brand.Entity;
				if (((previousValue != value) 
							|| (this._tbl_brand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_brand.Entity = null;
						previousValue.tbl_products.Remove(this);
					}
					this._tbl_brand.Entity = value;
					if ((value != null))
					{
						value.tbl_products.Add(this);
						this._id_brand = value.id_brand;
					}
					else
					{
						this._id_brand = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_brand");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
